### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pranshii**

### CODE REVIEW

**Comment by renancaraujo** [comment]
I did report you already.

**Comment by renancaraujo** [comment]
You are never getting the t-shirts.

**Comment by pranshii** [comment]
now let me report you stupid

**Comment by renancaraujo** [comment]
I am not dying for t-shirts.

**Comment by pranshii** [comment]
dying to talk to me?? get a life bro and let people be happy by doing
whatever they want ... buzz off now

**Comment by renancaraujo** [comment]
You have no idea how this practive affects the whole community. Its because of people like you that take shortcuts that the event will probably be cancelled.

**Pull request merged**
